config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Resource builds all crud action routes for blog
  # Using "AS" in the route wil create a variable for you to use in your code
    # :blog_post can reference two separate routes:
    # blog_post_path(1) -> "/blog_posts/1" or blog_post_url(1) -> "http://localhost:300/blog_posts/1"
    get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
    get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
    patch "/blog_posts/:id",to: "blog_posts#update"
    delete "/blog_posts/:id",to: "blog_posts#destroy"
    get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
    post "/blog_posts", to: "blog_posts#create", as: :blog_posts

  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  layout "application"
  def index
    @blog_posts = BlogPost.all
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :body)
  end

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog/index.html.erb
<div class="flex flex-col items-start justify-center px-4 md:items-center mt-28  sm:py-6 lg:py-0 ">

	<h1 class="text-4xl text-red-600 mb-8">Bloggggg!</h1>

	<%= @test %>

	<div class="flex items-center justify-center">
		<%= form_with(url: blog_path) do |form| %>


			<div class="space-y-4 mb-2">
				<div>
					<%= form.text_field :title  %>
				</div>

				<div>
					<%= form.text_area :body  %>
				</div>
			</div>

			<%= form.submit "Create Post", class:"text-white font-bold rounded-full px-4 py-2 bg-blue-600 hover:bg-blue-700 active:bg-blue-400 border border-black" %>

		<% end %> 
	</div>
</div>

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div class="font-bold text-red-600">
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="flex flex-col mt-2 mb-4">
    <%= form.label :title %>
    <%= form.text_field :title, class:"w-fit rounded-xl" %>
  </div>

  <div class="flex flex-col my-2">
    <%= form.label :body %>
    <%= form.text_area :body, class:"w-1/2 h-32 rounded-xl" %>
  </div>

  <%= form.submit class:"border py-2 px-4 border-gray-400 rounded-full" %>
<% end %>

app/views/blog_posts/create.html.erb
<div class="flex flex-col items-start justify-center w-full px-4 md:items-center mt-28 sm:py-6 lg:py-0 ">

	<h1 class="mb-8 text-4xl text-red-600">Create a Bloggggg!</h1>

	<div class="flex items-center justify-center">
		<%= form_with(url: blog_path) do |form| %>


			<div class="mb-2 space-y-4">
				<div>
					<%= form.text_field :title  %>
				</div>

				<div>
					<%= form.text_area :body  %>
				</div>
			</div>

			<%= form.submit "Create Post", class:"text-white font-bold rounded-full px-4 py-2 bg-blue-600 hover:bg-blue-700 active:bg-blue-400 border border-black" %>

		<% end %> 
	</div>
</div>

app/views/blog_posts/edit.html.erb
<div class="p-4">
  <h1 class="text-4xl font-semibold text-purple-700 ">
    Edit Blog Post
  </h1>

  <%= render partial: "form", locals: { blog_post: @blog_post } %>

  <%= button_to "Delete", @blog_post, method: :delete, data: { turbo_confirm: "Are you sure?" }, class:"text-white bg-red-600 rounded-full border border-black py-2 px-4 mt-2" %>
</div>

app/views/blog_posts/index.html.erb
<div class="flex items-center mt-12">

	<div class="w-full max-w-md mx-auto space-y-4 md:space-y-6 xl:max-w-xl">
		<h1 class="mb-8 text-4xl font-bold text-center text-black">
			Current Blogs
		</h1>


		<div class="grid grid-cols-2 p-2 bg-gray-100 border border-black rounded-xl">
			<% @blog_posts.each do |blog_post| %>
				<div class="flex flex-col items-center px-4 py-2 mb-4">
					<h2 class="text-2xl font-semibold text-center text-blue-600">
						<%= blog_post.title %>
					</h2>

					<p class="text-center">
						<%= blog_post.body %>
					</p>

					<div class="flex justify-center">
						<%= link_to "View", blog_post, class:"mt-2 rounded-full bg-purple-700 hover:bg-purple-900 cursor-auto active:bg-purple-600 border text-white border-black py-2 px-4 text-center font-medium" %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render partial: "form", locals: { blog_post: @blog_post }%>

app/views/blog_posts/show.html.erb
<div class="mt-12">

  <div class="w-1/2 p-4 mx-auto text-center bg-white border border-black rounded-xl">
    <h1 class="text-4xl font-bold text-center text-purple-900">
      <%= @blog_post.title %>
    </h1>

    <p class="mt-4 mb-4 font-medium text-center">
      <%= @blog_post.body %>
    </p>

  </div>
    <%= link_to "Edit", edit_blog_post_path, class:"text-white bg-blue-600 rounded-full border border-black py-2 px-4 mt-2" %>
    <%= link_to "Back", root_path, class:"text-white bg-blue-300 rounded-full border border-black py-2 px-4 mt-2" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/partials/head" %>

  <body class="">
    <div class="antialiased bg-gray-50 dark:bg-gray-900" >

      <!-- header nav -->
      <%= render "layouts/partials/header/nav" %>
      <!-- Sidebar -->
      <%= render "layouts/partials/sidebar/nav" %>

      <main class="h-auto p-4 pt-20 md:ml-64">

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <div>
        <% if user_signed_in? %>
          <%= link_to "Profile", edit_user_registration_path, class:"text-green-400 font-bold z-50" %>
          <%= button_to "log Out", destroy_user_session_path,  method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %>
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/partials/_head.html.erb
<head>
  <title>GoRailsBlog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="turbo-refresh-scroll" content="preserve">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

  <%= yield :head %>

  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

app/views/layouts/partials/header/_apps.html.erb
<!-- Apps -->
<button
  type="button"
  data-dropdown-toggle="apps-dropdown"
  class="px-4 py-2 text-black bg-purple-500 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600 group"
>
  <span class="sr-only">View notifications</span>
  <!-- Icon -->
  <%= icon("fa-solid", "layer-group", class:"text-lg group-hover:text-purple-600") %>
</button>
<!-- Dropdown menu -->
<div
  class="z-50 hidden max-w-sm my-4 overflow-hidden text-base list-none bg-white divide-y divide-gray-100 rounded shadow-lg dark:bg-gray-700 dark:divide-gray-600 rounded-xl"
  id="apps-dropdown"
>
  <div
    class="block px-4 py-2 text-base font-medium text-center text-gray-700 bg-gray-50 dark:bg-gray-600 dark:text-gray-300"
  >
    Apps
  </div>
  <div class="grid grid-cols-3 gap-4 p-4">
    <a
      href="#"
      class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group"
    >
      <svg
        aria-hidden="true"
        class="mx-auto mb-1 text-gray-400 w-7 h-7 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          fill-rule="evenodd"
          d="M10 2a4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z"
          clip-rule="evenodd"
        ></path>
      </svg>
      <div class="text-sm text-gray-900 dark:text-white">Sales</div>
    </a>
    <a
      href="#"
      class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group"
    >
      <svg
        aria-hidden="true"
        class="mx-auto mb-1 text-gray-400 w-7 h-7 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z"
        ></path>
      </svg>
      <div class="text-sm text-gray-900 dark:text-white">Users</div>
    </a>
    <a
      href="#"
      class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group"
    >
      <svg
        aria-hidden="true"
        class="mx-auto mb-1 text-gray-400 w-7 h-7 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          fill-rule="evenodd"
          d="M5 3a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2V5a2 2 0 00-2-2H5zm0 2h10v7h-2l-1 2H8l-1-2H5V5z"
          clip-rule="evenodd"
        ></path>
      </svg>
      <div class="text-sm text-gray-900 dark:text-white">Inbox</div>
    </a>
    <a
      href="#"
      class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group"
    >
      <svg
        aria-hidden="true"
        class="mx-auto mb-1 text-gray-400 w-7 h-7 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          fill-rule="evenodd"
          d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z"
          clip-rule="evenodd"
        ></path>
      </svg>
      <div class="text-sm text-gray-900 dark:text-white">
        Profile
      </div>
    </a>
    <a
      href="#"
      class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group"
    >
      <svg
        aria-hidden="true"
        class="mx-auto mb-1 text-gray-400 w-7 h-7 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          fill-rule="evenodd"
          d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
          clip-rule="evenodd"
        ></path>
      </svg>
      <div class="text-sm text-gray-900 dark:text-white">
        Settings
      </div>
    </a>
    <a
      href="#"
      class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group"
    >
      <svg
        aria-hidden="true"
        class="mx-auto mb-1 text-gray-400 w-7 h-7 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path d="M4 3a2 2 0 100 4h12a2 2 0 100-4H4z"></path>
        <path
          fill-rule="evenodd"
          d="M3 8h14v7a2 2 0 01-2 2H5a2 2 0 01-2-2V8zm5 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z"
          clip-rule="evenodd"
        ></path>
      </svg>
      <div class="text-sm text-gray-900 dark:text-white">
        Products
      </div>
    </a>
    <a
      href="#"
      class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group"
    >
      <svg
        aria-hidden="true"
        class="mx-auto mb-1 text-gray-400 w-7 h-7 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M8.433 7.418c.155-.103.346-.196.567-.267v1.698a2.305 2.305 0 01-.567-.267C8.07 8.34 8 8.114 8 8c0-.114.07-.34.433-.582zM11 12.849v-1.698c.22.071.412.164.567.267.364.243.433.468.433.582 0 .114-.07.34-.433.582a2.305 2.305 0 01-.567.267z"
        ></path>
        <path
          fill-rule="evenodd"
          d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-13a1 1 0 10-2 0v.092a4.535 4.535 0 00-1.676.662C6.602 6.234 6 7.009 6 8c0 .99.602 1.765 1.324 2.246.48.32 1.054.545 1.676.662v1.941c-.391-.127-.68-.317-.843-.504a1 1 0 10-1.51 1.31c.562.649 1.413 1.076 2.353 1.253V15a1 1 0 102 0v-.092a4.535 4.535 0 001.676-.662C13.398 13.766 14 12.991 14 12c0-.99-.602-1.765-1.324-2.246A4.535 4.535 0 0011 9.092V7.151c.391.127.68.317.843.504a1 1 0 101.511-1.31c-.563-.649-1.413-1.076-2.354-1.253V5z"
          clip-rule="evenodd"
        ></path>
      </svg>
      <div class="text-sm text-gray-900 dark:text-white">
        Pricing
      </div>
    </a>
    <a
      href="#"
      class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group"
    >
      <svg
        aria-hidden="true"
        class="mx-auto mb-1 text-gray-400 w-7 h-7 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          fill-rule="evenodd"
          d="M5 2a2 2 0 00-2 2v14l3.5-2 3.5 2 3.5-2 3.5 2V4a2 2 0 00-2-2H5zm2.5 3a1.5 1.5 0 100 3 1.5 1.5 0 000-3zm6.207.293a1 1 0 00-1.414 0l-6 6a1 1 0 101.414 1.414l6-6a1 1 0 000-1.414zM12.5 10a1.5 1.5 0 100 3 1.5 1.5 0 000-3z"
          clip-rule="evenodd"
        ></path>
      </svg>
      <div class="text-sm text-gray-900 dark:text-white">
        Billing
      </div>
    </a>
    <a
      href="#"
      class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group"
    >
      <svg
        aria-hidden="true"
        class="mx-auto mb-1 text-gray-400 w-7 h-7 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"
        ></path>
      </svg>
      <div class="text-sm text-gray-900 dark:text-white">
        Logout
      </div>
    </a>
  </div>
</div>

app/views/layouts/partials/header/_nav.html.erb
<nav class="fixed top-0 left-0 right-0 z-50 h-16 px-4 border-b border-gray-200 bg-gradient-to-b from-purple-800 via-purple-600 to-purple-800 dark:bg-gray-800 dark:border-gray-700">
  <div class="flex flex-wrap items-center justify-between h-full">

    <div class="flex items-center justify-start">
      <button
        data-drawer-target="drawer-navigation"
        data-drawer-toggle="drawer-navigation"
        aria-controls="drawer-navigation"
        class="px-4 py-2 mr-2 text-black rounded-lg cursor-pointer md:hidden hover:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 dark:focus:bg-gray-700 focus:ring-2 focus:ring-gray-100 dark:focus:ring-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
      >
        <%= icon("fa-solid", "bars", class:"text-lg") %>
        <span class="sr-only">Toggle sidebar</span>
      </button>
    </div>

    <div class="flex items-center space-x-4">
      <%= render "layouts/partials/header/notifications" %>
      <%= render "layouts/partials/header/apps" %>
      <%= render "layouts/partials/header/profile" %>
    </div>
  </div>
</nav>

app/views/layouts/partials/header/_profile.html.erb
<!-- Profile -->
<button
  type="button"
  class="px-4 py-2 mr-1 text-gray-500 bg-purple-500 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
  id="user-menu-button"
  aria-expanded="false"
  data-dropdown-toggle="dropdown"
>
  <span class="sr-only">Open user menu</span>
  <img
    class="w-8 h-8 rounded-lg"
    src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/michael-gough.png"
    alt="user photo"
  />
</button>
<!-- Dropdown menu -->
<div
  class="z-50 hidden w-56 my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600 rounded-xl"
  id="dropdown"
>
  <div class="px-4 py-3">
    <span
      class="block text-sm font-semibold text-gray-900 dark:text-white"
      >Neil Sims</span
    >
    <span
      class="block text-sm text-gray-900 truncate dark:text-white"
      >name@flowbite.com</span
    >
  </div>
  <ul
    class="py-1 text-gray-700 dark:text-gray-300"
    aria-labelledby="dropdown"
  >
    <li>
      <a
        href="#"
        class="block px-4 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white"
        >My profile</a
      >
    </li>
    <li>
      <a
        href="#"
        class="block px-4 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white"
        >Account settings</a
      >
    </li>
  </ul>
  <ul
    class="py-1 text-gray-700 dark:text-gray-300"
    aria-labelledby="dropdown"
  >
    <li>
      <a
        href="#"
        class="flex items-center px-4 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
        ><svg
          class="w-5 h-5 mr-2 text-gray-400"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
            clip-rule="evenodd"
          ></path>
        </svg>
        My likes</a
      >
    </li>
    <li>
      <a
        href="#"
        class="flex items-center px-4 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
        ><svg
          class="w-5 h-5 mr-2 text-gray-400"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z"
          ></path>
        </svg>
        Collections</a
      >
    </li>
    <li>
      <a
        href="#"
        class="flex items-center justify-between px-4 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
      >
        <span class="flex items-center">
          <svg
            aria-hidden="true"
            class="w-5 h-5 mr-2 text-primary-600 dark:text-primary-500"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M12.395 2.553a1 1 0 00-1.45-.385c-.345.23-.614.558-.822.88-.214.33-.403.713-.57 1.116-.334.804-.614 1.768-.84 2.734a31.365 31.365 0 00-.613 3.58 2.64 2.64 0 01-.945-1.067c-.328-.68-.398-1.534-.398-2.654A1 1 0 005.05 6.05 6.981 6.981 0 003 11a7 7 0 1011.95-4.95c-.592-.591-.98-.985-1.348-1.467-.363-.476-.724-1.063-1.207-2.03zM12.12 15.12A3 3 0 017 13s.879.5 2.5.5c0-1 .5-4 1.25-4.5.5 1 .786 1.293 1.371 1.879A2.99 2.99 0 0113 13a2.99 2.99 0 01-.879 2.121z"
              clip-rule="evenodd"
            ></path>
          </svg>
          Pro version
        </span>
        <svg
          aria-hidden="true"
          class="w-5 h-5 text-gray-400"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </a>
    </li>
  </ul>
  <ul
    class="py-1 text-gray-700 dark:text-gray-300"
    aria-labelledby="dropdown"
  >
    <li>
      <a
        href="#"
        class="block px-4 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
        >Sign out</a
      >
    </li>
  </ul>
</div>

app/views/layouts/partials/header/_search.html.erb
<form action="#" method="GET" class="hidden md:block md:pl-2">
  <label for="topbar-search" class="sr-only">Search</label>
  <div class="relative md:w-64 md:w-96">
    <div
      class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none"
    >
      <svg
        class="w-5 h-5 text-gray-500 dark:text-gray-400"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          fill-rule="evenodd"
          clip-rule="evenodd"
          d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
        ></path>
      </svg>
    </div>
    <input
      type="text"
      name="email"
      id="topbar-search"
      class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full pl-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
      placeholder="Search"
    />
  </div>
</form>

app/views/layouts/partials/sidebar/_components.html.erb
<li class="group">
  <a
    href="#"
    class="flex items-center p-2 text-base font-medium text-gray-900 transition duration-75 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 dark:text-white group-hover:text-purple-600">
    <%= icon("fa-solid", "folder", class:"text-black group-hover:text-purple-600") %>
    <span class="ml-3">Components</span>
  </a>
</li>